#!/usr/bin/env sh

dir=$(dirname $0)
cd ${dir//script/}
echo "Enter your post title and press <enter>:"
read title
file=$(awk '{print tolower($0)}' <<< "_posts/$(date '+%Y-%m-%d')-${title// /-}.md")
touch $file
echo "---\nlayout: post\ntitle: $@\ndate: $(date '+%Y-%m-%d %H:%M:%S %z')\ntags: \n---\n\n" > $file
open $file
